// Precompiled header

// Qt
#include <QObject>
#include <QVector>
#include <QHash>
#include <QMap>
#include <QList>
#include <QString>
#include <QStringList>
#include <QColor>
#include <QFont>
#include <QVariant>
#include <QPointer>
#include <QDir>
#include <QFile>
#include <QPoint>
#include <QRect>
#include <QRectF>
#include <QAbstractItemModel>
#include <QAbstractTableModel>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsRectItem>
#include <QApplication>
#include <QTimer>
#include <QFileDialog>
#include <QPushButton>
#include <QLabel>
#include <QCheckBox>
#include <QComboBox>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QDrag>
#include <QMimeData>
#include <QToolButton>
#include <QFrame>
#include <QValidator>
#include <QAction>
#include <QButtonGroup>
#include <QHeaderView>
#include <QLineEdit>
#include <QSpacerItem>
#include <QStackedWidget>
#include <QRadioButton>
#include <QTabWidget>
#include <QToolTip>
#include <QMouseEvent>
#include <QStyle>

// std
#include <string>
#include <set>
#include <map>
#include <memory>
#include <vector>
#include <unordered_map>
#include <array>
#include <bitset>
#include <initializer_list>
#include <functional>
#include <algorithm>
#include <numeric>
#include <iterator>
#include <type_traits>
#include <cmath>
#include <cassert>
#include <cfloat>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <thread>
#include <condition_variable>
